---

- name: Install the nodesource yum repository
  yum:
    name: '{{ nodesource_repo_url }}'
    state: present

- name: Install nodejs
  yum:
    name: nodejs
    state: present
    update_cache: yes
