---

- name: Install the nodejs yum repository
  shell: >
    curl -sL {{ nodejs_setup_url }} | bash -
  args:
    warn: "no"
    creates: "{{ nodejs_repo_path }}"

- name: Install nodejs
  yum:
    name: "nodejs"
    state: "present"
    update_cache: "yes"
